---
- name: "Base YML file"
  hosts: localhost
  connection: local
  become: true
  tasks:
  
    - name: "Update and upgrade installed packages"
      apt:
        update_cache: true
        upgrade: full
        autoremove: true

    - name: "Install software-properties-common"
      apt:
        name: software-properties-common

    - name: "Install vim"
      apt:
        name: vim
        state: present
