---
- name: "Install KVM / QEMU"
  hosts: localhost
  connection: local
  become: true
  tasks:
  
    - name: "Install kvm"
      apt:
        name: 
          - qemu-kvm 
          - libvirt-daemon-system 
          - libvirt-clients 
          - bridge-utils 
          - virt-manager  

    - name: "Enable libvirtd in systemd"
      systemd_service:
        - name: libvirtd
          state: started
          enabled: true
