---
- name: Setup Podman
  hosts: localhost
  connection: local
  tasks:

    - name: "Install podman"
      become: true
      apt:
        name: podman
      register: podman_status
      
    - name: "Initialise podman - machine init"
      shell: podman machine init
      when: podman_status.changed

    - name: "Initialise podman - machine start"
      shell: podman machine start
      when: podman_status.changed

    - name: "Install Podman Desktop (flatpak)"
      community.general.flatpak:
        method: user
        name: io.podman_desktop.PodmanDesktop
        remote: flathub
        state: present
      when: podman_status.changed

